### ISSUE TITLE
PIC32MZDA - 2DGPU works, GFX2D doesn't

### ISSUE THREAD

**Issue by LuisCRSousa** [Microchip-MPLAB-Harmony/gfx#8]
I've been working 2DGPU  and it works ok, But if I change the graphic processor to GFX2D the project don't compile and it gives not defined errors and so many others.

`drv_gfx2d_hal.c:143:30: error: variable 'orientation' set but not used [-Werror=unused-but-set-variable]
GFX2D_TRANSFER_DIRECTION orientation = GFX2D_XY00;
drv_gfx2d_hal.c:70:19: error: 'drawLine' defined but not used [-Werror=unused-function]
 static GFX_Result drawLine(const GFX_Point* p1,
drv_gfx2d.c:79:5: error: implicit declaration of function 'PLIB_GFX2D_Initialize' [-Werror=implicit-function-declaration]
PLIB_GFX2D_Initialize();`

and many others similar errors.

Wanted to change the driver to gfx2d because it is listed as production release and 2dgpu is listed as beta

**Comment by MHGC** [comment]
As a standard policy, a library that has been unchanged for two consecutive releases where were new features added.  There is a mislabelling here.  The 2DGPU library should be the one in production and GFX2D in beta.

As for the build errors, they will be fixed in gfx-v3.6.0 (with JIRA MH3-24677).

The GFX2D library is intended for a different GPU that is on the SAM 9x60.  It is not meant for PIC32MZ DA.

We will make sure GFX2D is not selectable from within the MHC for a PIC32MZDA project with a fix for MH3-29689.
